FROM node:16.18.0-alpine3.16
RUN addgroup app && adduser -S -G app app
USER app
WORKDIR /app
COPY package*.json .
RUN ["npm", "install"]
COPY . .
ENV REACT_APP_BASE_URL=http://ec2-34-228-184-187.compute-1.amazonaws.com:8000/
EXPOSE 3000
CMD ["npm", "start"]