USE FormSubmissions

CREATE TABLE SUBMISSIONS (SUBMISSION_ID INT PRIMARY KEY,
									EMAIL NVARCHAR(100) NOT NULL,
									SUBMITTER_NAME NVARCHAR(100) NOT NULL,
									AGENTNAME NVARCHAR(100) NOT NULL,
									AGENT_COMMENTS NVARCHAR(100),
									ADDITIONAL_COMMENTS  NVARCHAR(100),
									STREET_ADDRESS NVARCHAR(100) NOT NULL,
									IMAGES_LOCATION NVARCHAR(200) NOT NULL,
									PDF_LOCATION NVARCHAR(200) NOT NULL
								)

CREATE TABLE SUBMISSION_IMAGES (SUBMISSION_ID INT,
								HOUSE_AREA NVARCHAR(100),
								IMAGE_NAME NVARCHAR(100),
								IMAGE_LOCATION NVARCHAR(200)
								CONSTRAINT PK_SUBMISSION_INFO
								PRIMARY KEY (SUBMISSION_ID,HOUSE_AREA, IMAGE_NAME, IMAGE_LOCATION ))


CREATE TABLE SUBMISSION_PDFS (SUBMISSION_ID INT PRIMARY KEY,
							PDF_NAME NVARCHAR(100),
							PDF_LOCATION NVARCHAR(200))
